Otzovik/Otzovik/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Otzovik/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import login_view, logout_view, RegisterView, ProfileView, ChangeProfileView, ChangePasswordView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', ChangeProfileView.as_view(), name="change_profile"),
    path('change/password/', ChangePasswordView.as_view(), name="change_password"),
]

Otzovik/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, CreateReview, UpdateView, DeleteView, IndexViewProducts, CreateProduct, \
    ProductView, UpdateProduct, DeleteProduct

app_name = "webapp"

urlpatterns = [
    path('', IndexViewProducts.as_view(), name="index_product"),
    path('projects/add/', CreateProduct.as_view(), name="create_product"),
    path('project/<int:pk>/', ProductView.as_view(), name="product_view"),
    path('reviews/', IndexView.as_view(), name="index"),
    path('reviews/add/', CreateReview.as_view(), name="create_review"),
    path('review/<int:pk>/update', UpdateView.as_view(), name="update_review"),
    path('review/<int:pk>/delete', DeleteView.as_view(), name="delete_review"),
    path('project/<int:pk>/update', UpdateProduct.as_view(), name="update_product"),
    path('project/<int:pk>/delete', DeleteProduct.as_view(), name="delete_product"),
]

Otzovik/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.


class Profile(models.Model):
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True, verbose_name="Аватар")
    github = models.URLField(max_length=100, null=True, blank=True)
    about = models.TextField(max_length=3000, null=True, blank=True, verbose_name="Описание")
    user = models.OneToOneField(get_user_model(),
                                on_delete=models.CASCADE,
                                verbose_name="Пользователь",
                                related_name="profile")

Otzovik/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    email = forms.CharField(required=True)

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        if not first_name and not last_name:
            raise ValidationError("Заполните имя или фамилию")


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['github', 'about', 'avatar']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

Otzovik/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

# Create your views here.\
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from accounts.models import Profile


class RegisterView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


# def register_view(request):
#     form = MyUserCreationForm()
#     if request.method == 'POST':
#         form = MyUserCreationForm(data=request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             return redirect('webapp:index')
#     return render(request, 'registration.html', {'form': form})


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


class ProfileView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = "profile.html"
    paginate_by = 6
    paginate_orphans = 0
    context_object_name = "user_obj"

    def get_context_data(self, **kwargs):
        paginator = Paginator(self.get_object().reviews.all(),
                              self.paginate_by,
                              self.paginate_orphans)
        page_number = self.request.GET.get('page', 1)
        page_object = paginator.get_page(page_number)
        context = super().get_context_data(**kwargs)
        context['page_obj'] = page_object
        context['products'] = page_object.object_list
        context['is_paginated'] = page_object.has_other_pages()
        return context


class ChangeProfileView(PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = "change_user.html"
    profile_form_class = ProfileChangeForm
    context_object_name = "user_obj"

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "profile_form" not in context:
            context["profile_form"] = self.profile_form_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        profile_form = self.profile_form_class(instance=self.object.profile,
                                               data=request.POST,
                                               files=request.FILES)
        if form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        # self.get_form()
        form.save()
        profile_form.save()
        return redirect("accounts:profile", self.object.pk)

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form, profile_form=profile_form))


class ChangePasswordView(PasswordChangeView):
    # model = User
    # form_class = PasswordChangeForm
    template_name = "change_password.html"

    # def get_object(self, queryset=None):
    #     return self.request.user

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.request.user.pk})

    # def form_valid(self, form):
    #     result = super().form_valid(form)
    #     update_session_auth_hash(self.request, self.object)
    #     return result

Otzovik/accounts/templates/change_password.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Изменение пароля</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Изменить" %}
        </form>
    </div>
{% endblock %}

Otzovik/accounts/templates/change_user.html
{% extends "base.html" %}

{% block content %}
    <div class="text-center">
        <h1>Редактирование профиля</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% include "partial/form.html" with fields_only=True %}
            {% include "partial/form.html" with form=profile_form button_text="Редактировать"%}
        </form>
    </div>
{% endblock %}

Otzovik/accounts/templates/login.html
{% extends "base.html" %}

{% block title %}Вход{% endblock %}
{% block content %}
    <h1>Вход</h1>
    <div class="text-center">
        <form action="" method="post" class="w-50 ms-auto me-auto">
            {% csrf_token %}
            {% if has_error %}
                <p class="text-danger">Неверное имя пользователя или пароль.</p>
            {% endif %}
            <div class="form-group">
                <label for="username" class="form-label">Имя пользователя:</label>
                <input type="text" name="username" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Пароль:</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <button class="mt-3 btn btn-outline-dark" type="submit">Войти</button>
        </form>
    </div>
{% endblock %}

Otzovik/accounts/templates/profile.html
{% extends "base.html" %}

{% block title %}Профиль{% endblock %}
{% block nav %}
    {% if user_obj == user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_profile' user_obj.pk %}">Редактировать</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_password' %}">Сменить пароль</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card flex-row mt-3">
        {% if user_obj.profile.avatar %}
            <img src="{{ user_obj.profile.avatar.url }}" class="card-img-top w-25" alt="...">
        {% endif %}
        <div class="card-body ms-5">
            <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Гитхаб: {{ user_obj.profile.github }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">О себе: {{ user_obj.profile.about }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Имя: {{ user_obj.first_name }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Фамилия: {{ user_obj.last_name }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Почта: {{ user_obj.email }}</h6>
        </div>
    </div>
    {% for review in user_obj.reviews.all %}
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h3>{{ review.user }}</h3>
                    <h3>{{ review.review }}</h3>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

Otzovik/accounts/templates/registration.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}
{% block content %}
    <h1>Регистрация</h1>
    <form action="" method="post">
        {% include 'partial/form.html' with button_text='Зарегистрироваться' %}
    </form>
{% endblock %}