Otzovik/Otzovik/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Otzovik/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import login_view, logout_view, RegisterView, ProfileView, ChangeProfileView, ChangePasswordView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', ChangeProfileView.as_view(), name="change_profile"),
    path('change/password/', ChangePasswordView.as_view(), name="change_password"),
]

Otzovik/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, CreateReview, UpdateView, DeleteView, IndexViewProducts, CreateProduct, \
    ProductView, UpdateProduct, DeleteProduct

app_name = "webapp"

urlpatterns = [
    path('', IndexViewProducts.as_view(), name="index_product"),
    path('projects/add/', CreateProduct.as_view(), name="create_product"),
    path('project/<int:pk>/', ProductView.as_view(), name="product_view"),
    path('reviews/', IndexView.as_view(), name="index"),
    path('reviews/add/', CreateReview.as_view(), name="create_review"),
    path('review/<int:pk>/update', UpdateView.as_view(), name="update_review"),
    path('review/<int:pk>/delete', DeleteView.as_view(), name="delete_review"),
    path('project/<int:pk>/update', UpdateProduct.as_view(), name="update_product"),
    path('project/<int:pk>/delete', DeleteProduct.as_view(), name="delete_product"),
]

Otzovik/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


DEFAULT_CATEGORY = 'other'
CATEGORY_CHOICES = (
    (DEFAULT_CATEGORY, 'Разное'),
    ('food', 'Еда'),
    ('drink', 'Напитки'),
    ('zakuski', 'Закуски'),
    ('eat', 'Еда'),
)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    category = models.CharField(max_length=20, default=DEFAULT_CATEGORY, choices=CATEGORY_CHOICES,
                                verbose_name='Категория')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    image = models.ImageField(upload_to="image", null=True, blank=True,
                              verbose_name="Картинка")

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.pk})

    def get_average(self):
        average = self.reviews.mark * len(self.reviews)
        print(average)
        return average["total"]

    class Meta:
        db_table = "products"
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Review(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="reviews",
                             verbose_name='Пользователь')
    product = models.ForeignKey('webapp.Product', related_name='reviews',
                                 verbose_name='Продукт', on_delete=models.CASCADE)
    review = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Отзыв')
    mark = models.PositiveIntegerField(verbose_name='оценка')
    bool = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    def __str__(self):
        return f'{self.user}'

    # def get_absolute_url(self):
    #     return reverse("webapp:product_view", kwargs={"pk": self.pk})

    class Meta:
        db_table = "reviews"
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

Otzovik/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets

from webapp.models import Product, Review


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "category", "description", "image"]
        widgets = {
            "description": widgets.Textarea(attrs={"placeholder": "Введите описание"})
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['product', "review", "mark", "bool"]
        widgets = {
            "review": widgets.Textarea(attrs={"placeholder": "Введите отзыв"})
        }

    def clean_mark(self):
        mark = self.cleaned_data.get("mark")
        if mark > 5:
            raise ValidationError("Оценка не должна быть больше 5")
        if mark < 1:
            raise ValidationError("Оценка не должна быть меньше 1")
        return mark


class ProductDeleteForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name"]

    def clean_title(self):
        name = self.cleaned_data.get("name")
        if self.instance.name != name:
            raise ValidationError("Названия не совпадают")
        return name


class ReviewDeleteForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["review"]

    def clean_title(self):
        review = self.cleaned_data.get("review")
        if self.instance.name != review:
            raise ValidationError("Названия не совпадают")
        return review

Otzovik/webapp/views/base_view.py
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils.http import urlencode
from django.views import View
from django.views.generic import ListView, TemplateView

from webapp.forms import SearchForm


class SearchView(ListView):
    search_form_class = SearchForm
    search_form_field = "search"
    query_name = "query"
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return self.model.objects.filter(self.get_query())
        return self.model.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({self.search_form_field: self.search_value})
            context[self.query_name] = query
            context[self.search_form_field] = self.search_value
        return context

    def get_search_form(self):
        return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get(self.search_form_field)

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query


class ListView(TemplateView):
    model = None
    context_key = "objects"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_objects()
        return context

    def get_objects(self):
        return self.model.objects.all()


class FormView(View):
    form_class = None
    template_name = None
    redirect_url = ""

    def get_redirect_url(self):
        return redirect(self.redirect_url)

    def get(self, request):
        form = self.form_class()
        context = self.get_context(form=form)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_isvalid(form)

    def get_context(self, **kwargs):
        return kwargs

    def form_valid(self, form):
        return self.get_redirect_url()

    def form_isvalid(self, form):
        context = self.get_context(form=form)
        return render(self.request, self.template_name, context)

Otzovik/webapp/views/products.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy

# Create your views here.
from django.utils.http import urlencode

from webapp.forms import ProductForm, SearchForm, ProductDeleteForm
from webapp.models import Product
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


class IndexViewProducts(ListView):
    model = Product
    template_name = "products/index.html"
    context_object_name = "products"
    ordering = "-updated_at"
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return Product.objects.filter(
                Q(name__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return Product.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({'search': self.search_value})  # search=dcsdvsdvsd
            context['query'] = query
            context['search'] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("search")


class ProductView(DetailView):
    template_name = "products/product_view.html"
    model = Product
    context_object_name = "products"
    ordering = "-updated_at"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = self.object.reviews.order_by("-created_at")
        return context

    # def has_permission(self):
    #     return super().has_permission() and self.request.user in self.get_object().users.all() or \
    #            super().has_permission() and self.request.user.groups.filter(name__in=("Moderator",)).exists()


class CreateProduct(PermissionRequiredMixin, CreateView):
    form_class = ProductForm
    template_name = "products/create.html"
    permission_required = "webapp.add_project"

    def has_permission(self):
        return self.request.user.has_perm("webapp.change_product")

    # def form_valid(self, form):
    #     project = form.save(commit=False)
    #     project.save()
    #     form.save_m2m()
    #     return redirect("webapp:project_view", pk=project.pk)


class UpdateProduct(PermissionRequiredMixin, UpdateView):
    form_class = ProductForm
    template_name = "products/update.html"
    model = Product
    permission_required = "webapp.change_product"


class DeleteProduct(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = "products/delete.html"
    success_url = reverse_lazy('webapp:index_product')
    form_class = ProductDeleteForm
    permission_required = "webapp.delete_product"

Otzovik/webapp/views/reviews.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
# Create your views here.
from django.utils.http import urlencode
from django.views import View
from django.views.generic import TemplateView, FormView, ListView, UpdateView, DeleteView, CreateView

from webapp.views.base_view import FormView as CustomFormView
from webapp.forms import ReviewForm, SearchForm, ReviewDeleteForm
from webapp.models import Review, Product


class IndexView(ListView):
    model = Review
    template_name = "reviews/index.html"
    context_object_name = "reviews"
    ordering = "-updated_at"
    paginate_by = 5
    permission_required = "webapp.view_review"

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return Review.objects.filter(
                Q(name__icontains=self.search_value))
        return Review.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({'search': self.search_value})  # search=dcsdvsdvsd
            context['query'] = query
            context['search'] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("search")


class CreateReview(LoginRequiredMixin, CreateView):
    form_class = ReviewForm
    template_name = "reviews/create.html"

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})

    # def form_valid(self, form):
    #     self.review = form.save()
    #     return super().form_valid(form)
    #
    # def get_redirect_url(self):
    #     return redirect("webapp:product_view", pk=self.review.pk)


class UpdateReview(PermissionRequiredMixin, UpdateView):
    form_class = ReviewForm
    template_name = "reviews/update.html"
    model = Review
    permission_required = "webapp.change_review"

    def has_permission(self):
        return super().has_permission() or self.request.user in self.get_object().project.users.all()


class DeleteReview(PermissionRequiredMixin, DeleteView):
    model = Review
    template_name = "reviews/delete.html"
    success_url = reverse_lazy('webapp:index')
    form_class = ReviewDeleteForm
    permission_required = "webapp.delete_review"

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.users.all()

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, instance=self.get_object())
        if form.is_valid():
            return self.delete(request, *args, **kwargs)
        else:
            return self.get(request, *args, **kwargs)

Otzovik/webapp/templates/products/create.html
{% extends "base.html" %}
{% block title %}Редактирование участников{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Редактирование участников</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Сохранить" %}
        </form>
    </div>
{% endblock %}

Otzovik/webapp/templates/products/delete.html
{% extends "base.html" %}
{% block title %}Удаление проекта{% endblock %}

{% block content %}
    <h2>Введите название проекта ({{ project.name }}) для удаления</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% include "partial/form.html" with button_text="Удалить" %}
    </form>
{% endblock %}

Otzovik/webapp/templates/products/index.html
{% extends "base.html" %}
{% load static %}
{% block nav %}
    {% if perms.webapp.add_product %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:create_product" %}">Создание продукта</a>
        </li>
    {% endif %}
    {#        {% if request.user.is_authenticated %}#}
    {#            <li class="nav-item">#}
    {#                <a class="nav-link" href="{% url "webapp:create_project" %}">Создание задания</a>#}
    {#            </li>#}
    {#        {% endif %}#}
    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:index" %}">Все продукты</a>
    </li>
{% endblock %}
{% block content %}
    {% include "partial/search.html" %}
    {% include "partial/priducts_list_partial.html" %}
{% endblock %}

Otzovik/webapp/templates/products/product_view.html
{% extends "base.html" %}
{% block nav %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:create_review" %}">Оставить отзыв</a>
        </li>
        {% if perms.webapp.change_product %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "webapp:update_product" products.pk %}">Редактировать</a>
            </li>
        {% endif %}
        {% if perms.webapp.delete_product %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "webapp:delete_product" products.pk %}">Удалить</a>
            </li>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    {% if products.image %}
        <img src="{{ products.image.url }}" class="card-img-top w-25" alt="...">
    {% else %}
        <img src="/images/18741522.jpg/" class="card-img-top w-25" alt="">
    {% endif %}
    <p>
        {{ products.name }}
    </p>
    <p>
        {{ products.category }}
    </p>
    <p>
        {{ products.description }}
    </p>
    <h3>Отзывы</h3>
    {#    {% for review in reviews %}#}
    {#        <p>{{ review.user }}</p>#}
    {#    {% endfor %}#}
    <div class="row">
        {% for review in reviews %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <span><a
                                href="{% url "accounts:profile" review.user.pk %}">{{ review.user.username }}</a>,</span>
                        <h3>{{ review.user.email }}</h3>
                        <h3>{{ review.review }}</h3>
                        <h3>{{ review.mark }}</h3>
                        {% if perms.webapp.delete_review %}
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url "webapp:delete_review" review.pk %}">Удалить</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "webapp:update_review" review.pk %}">Редактировать</a>
                            </li>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if is_paginated %}
            {% include "partial/pagination.html" %}
        {% endif %}
    </div>
    <a href="{% url "webapp:index_product" %}">На главную</a>
    <div class="modal fade" id="projectDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="taskDeleteModal">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Вы уверены что хотите удалить продукт? {{ product.name }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{% url "webapp:delete_product" products.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Да</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Otzovik/webapp/templates/products/update.html
{% extends "base.html" %}
{% block title %}Изменение задания{% endblock %}

{% block content %}
    <h1>Update Task</h1>
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Изменить"%}
    </form>
    <a href="{% url "webapp:index_product" %}">На главную</a>
{% endblock %}